binary_build_commands: go install
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: make test
zz_generated_metadata:
  branch: master
  org: openshift
  repo: backplane-api
